name: Docker Image Push to Hub

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: build images
      working-directory: ./slam_ros
      run: make image image_CUDA tag tag_cuda
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
        repository: ${{ github.DOCKER_HUB_USER }}/slam_ros:latest
        tag_with_ref: true
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}
        repository: ${{ github.DOCKER_HUB_USER }}/slam_ros:cuda
        tag_with_ref: true  
