name: Docker Image Push to Hub

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        working-directory: ./slam_ros
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          repository: arthav24/slam_ros
          tags: latest