name: Docker Image Push to Hub

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Build images
      run: make image image_CUDA
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: arthav24
        password: 35e6c51a-e7eb-403b-8d67-f0b897fafd86
    - name: Tag images
      run: docker tag slam_ros:latest arthav24/slam_ros:latest && docker tag  slam_ros:cuda arthav24/slam_ros:cuda
    
    
